// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDozohKOqHn_BltwtfZtv44ItTyHCUezz4',
    appId: '1:275570956029:web:7e65d87d05b8c05be5d094',
    messagingSenderId: '275570956029',
    projectId: 'abt-proje',
    authDomain: 'abt-proje.firebaseapp.com',
    storageBucket: 'abt-proje.appspot.com',
    measurementId: 'G-QSK9NJNC51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaBPs-ihP2TzYmMpRUMbHZBuIDPLIt34k',
    appId: '1:275570956029:android:1adfab4be19b61dde5d094',
    messagingSenderId: '275570956029',
    projectId: 'abt-proje',
    storageBucket: 'abt-proje.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYDrrgVdtkVxPU8AYgRhfExG0JbjRu-44',
    appId: '1:275570956029:ios:cf9481700e1c2283e5d094',
    messagingSenderId: '275570956029',
    projectId: 'abt-proje',
    storageBucket: 'abt-proje.appspot.com',
    iosClientId: '275570956029-cthala19j47q62o13i9jtj4aqnc8rntk.apps.googleusercontent.com',
    iosBundleId: 'com.example.abtProje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYDrrgVdtkVxPU8AYgRhfExG0JbjRu-44',
    appId: '1:275570956029:ios:cf9481700e1c2283e5d094',
    messagingSenderId: '275570956029',
    projectId: 'abt-proje',
    storageBucket: 'abt-proje.appspot.com',
    iosClientId: '275570956029-cthala19j47q62o13i9jtj4aqnc8rntk.apps.googleusercontent.com',
    iosBundleId: 'com.example.abtProje',
  );
}
